services:
    web:
        build: .
        # 映射端口 【宿主机端口:容器端口】
        ports:
            - "80:80"
            - "443:443"
        # 容器名称
        container_name: test
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        restart: always
        # 相当于 docker run -i
        stdin_open: true
        # 相当于 docker run -t
        tty: true
        networks:
          - ipv6test

networks:
  ipv6test:
    name: diynet6
    driver: bridge
